name: CircleDeveloperAPI
version: '1.1.1'
main: de.synccircle.circledeveloperapi.CircleDeveloperAPI
api-version: '1.21'
authors: [ SyncCircle ]

commands:
  circledeveloperapi:
    permission: circle.command.circledeveloperapi

permissions:
  circle.command.circledeveloperapi:
    description: ''
  circle.command.circledeveloperapi.reload:
    description: ''
  circle.command.circledeveloperapi.reload.messages:
    description: ''
